version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: finance-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - finance_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finance"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: finance-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ../backend
      target: dev        # prod-hoz: target: prod és vedd ki a volume-ot
    container_name: finance-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/finance
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: devsecret_change_me
      # további környezeti változók...
    volumes:
      - ../backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      # ajánlott egy GET /healthz endpoint a FastAPI-ban
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  worker:
    build:
      context: ../backend
      target: worker
    container_name: finance-worker
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/finance
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: devsecret_change_me
    volumes:
      - ../backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend
      target: dev       # prod-hoz: target: prod és volume-ok nélkül
    container_name: finance-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE: http://localhost:8000
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_started

volumes:
  finance_pg_data:
